import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';
import { Sparkles } from 'lucide-react';
import type { DailyBriefing as Briefing } from '@/types';
import type { Derived } from '@/hooks/useDerived';
import { useAuthStore } from '@/store/useAuthStore';
import { briefingService } from '@/services';
import { GlassCard } from '@/components/ui/GlassCard';
import { Skeleton } from '@/components/ui/Feedback';

/**
 * Daily Briefing card. Uses briefingService.generateDailyBriefing(), which is
 * rule-based today and the swap-in point for a real AI call later.
 */
export function DailyBriefingCard({ d, className }: { d: Derived; className?: string }) {
  const user = useAuthStore((s) => s.user);
  const [briefing, setBriefing] = useState<Briefing | null>(null);

  useEffect(() => {
    let alive = true;
    void briefingService.generateDailyBriefing(d.snapshot, user, d.input).then((b) => alive && setBriefing(b));
    return () => {
      alive = false;
    };
  }, [d, user]);

  return (
    <GlassCard
      className={className}
      eyebrow={
        <span className="flex items-center gap-1.5">
          <Sparkles className="h-3 w-3 text-amber" aria-hidden /> Daily briefing
        </span>
      }
      title="Today in three lines"
      hover={false}
      glow="rgb(var(--amber) / 0.6)"
    >
      {!briefing ? (
        <div className="space-y-2">
          <Skeleton className="h-6 w-2/3" />
          <Skeleton className="h-4 w-full" />
          <Skeleton className="h-4 w-5/6" />
        </div>
      ) : (
        <div aria-live="polite">
          <ul className="space-y-2">
            {briefing.lines.slice(0, 3).map((l, i) => (
              <motion.li
                key={l}
                initial={{ opacity: 0, x: -6 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.1 + i * 0.08 }}
                className="flex gap-2.5 text-sm leading-relaxed text-muted"
              >
                <span aria-hidden className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-[linear-gradient(135deg,rgb(var(--violet)),rgb(var(--cyan)))]" />
                {l}
              </motion.li>
            ))}
          </ul>
          <p className="mt-4 font-mono text-[10px] uppercase tracking-widest text-faint">
            {briefing.generatedBy === 'ai' ? 'Generated by AI' : 'Generated from your plan'}
          </p>
        </div>
      )}
    </GlassCard>
  );
}
